### ISSUE TITLE
Building Simple Project

### ISSUE THREAD

**Issue by pslach** [bazelbuild/rules_dotnet#110]
I'm trying to build a very simple project that outputs a .dll. This project has one file with a single method that returns a string. My WORSPACE is right from the README as follows:

```
git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    commit = "4a255eefbe099e2b3cd665baa407617fa27b6ad9",
)

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_register_sdk", "net_register_sdk", "mono_register_sdk", "dotnet_register_toolchains", "dotnet_repositories", "nuget_package")

dotnet_register_toolchains()
dotnet_repositories()
core_register_sdk("v2.1.502", name = "core_sdk")
net_register_sdk("net471", name = "net_sdk")
mono_register_sdk()
```

My BUILD file is also very simple:

```
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_library")

dotnet_library(
  name = "api",
  srcs = ["HelloWorld.cs"],
)
```

When I try to build this target I get:

> external/io_bazel_rules_dotnet/BUILD:6:1: every rule of type dotnet_context_data implicitly depends upon the target '@dotnet_sdk//:mcs_bin', but this target could not be found because of: no such package '@dotnet_sdk//'

My understanding was that the calls to dotnet_register_toolchains(), dotnet_repositories(), etc... should have set everything up by having Bazel download all the required libraries.

Am I misunderstanding this? 

I'm running on MacOS.

Thanks in advance.

**Comment by tomaszstrejczek** [comment]
Adding the following to your BUILD file next to the WORKSPACE file should help:

**Comment by ozio85** [comment]
Hi, I encountered the same problem on Windows.. but i don't know if it has the same origin on Mac.

I had only Microsoft DotNet Framework installed, and i encountered the same problem (would be the same only having DotNet core installed).

I noticed that currently you HAVE TO install Mono, otherwise I get the "no such package '@dotnet_sdk//'" on Windows as well. Once I installed Mono, everything worked fine.

**Comment by pslach** [comment]
Hi,

I applied the changes and now I'm getting a different error:

```
api/BUILD:3:1: Compiling api:api failed (Exit 2) mono failed: error executing command external/dotnet_sdk/mono_bin/mono external/dotnet_sdk/mcs_bin/mcs.exe /noconfig @bazel-out/darwin-fastbuild/bin/api/api.dll.param

Use --sandbox_debug to see verbose messages from the sandbox
Cannot open assembly 'external/dotnet_sdk/mcs_bin/mcs.exe': No such file or directory.
Target //api:api failed to build
```

I looked in bazel-bazel_net/external/dotnet_sdk/mcs_bin and mcs.exe does exist in there. Perhaps it's not looking under the bazel-bazel_net root folder? Btw bazel_net is the containing folder for my project so that is where that name is coming from.

**Comment by tomaszstrejczek** [comment]
Rules_dotnet are unable to download .NET and Mono. Since you use in the WORKSPACE net_register_sdk() and mono_register_sdk(), it tries to locate them in well known locations. It looks like the rules fail to find Mono. If you intend to use Mono you have to install it. If not, please remove mono_register_sdk() from the WORKSPACE file and dotnet_context_data() from the BUILD file.

**Comment by byang223** [comment]
I'm having this issue on Mac as well. @pslach did you come up with a solution?

**Comment by tomaszstrejczek** [comment]
@byang223 Could you attach you WORKSPACE and BUILD file in the main directory? I would like to reproduce the problem.

**Comment by byang223** [comment]
I actually figured out why mine wasn't working. I was trying to use both mono and net sdk and I had a mix up on the library type. It's working correctly now :)
