### ISSUE TITLE
Support for arm64?

### ISSUE THREAD

**Issue by ironpeak** [bazelbuild/rules_dotnet#255]
I noticed there is no toolchain for arm64 (only amd64), does this rule work for arm architecture?

https://github.com/bazelbuild/rules_dotnet/blob/master/dotnet/toolchain/toolchains.bzl

**Comment by purkhusid** [comment]
@ironpeak Are you using a Mac or Linux ARM? I've got a private patch that makes .Net 5.0 work on MacOS using ARM that I could upstream. Since .Net 5 does not support MacOS ARM natively(It's coming in .Net 6) it will use Rosetta to run the .Net binaries.

This patch works for the devs at my company that are using MacOS ARM. If you are interested i can create a PR to the repo with it if @tomaszstrejczek is willing to accept it.

**Comment by ironpeak** [comment]
We are using MacOS. I see .Net 6 is only about a month away so I'll wait for the native support.

We haven't started using dotnet at my company yet, so there is no rush.

**Comment by purkhusid** [comment]
MacOS Arm is now both supported on `master` and the WIP `next` branch.
