### ISSUE TITLE
Is there an equivalent to dotnet publish?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#280]
Using `dotnet publish` it is possible to generate a folder with a DLL and all of its dependencies. 

Is there an equivalent in `rules_dotnet`?

**Comment by purkhusid** [comment]
@njlr There is no such support at the moment in these rules. Can I ask what the exact use case you have is?

**Comment by njlr** [comment]
For example to deploy an AWS Lambda it is necessary to build a `.zip` that contains the .NET library and any dependencies.

**Comment by purkhusid** [comment]
I went with using containers and AWS lambda instead of the ZIP since I already had the whole container building workflow setup in our repo

**Comment by njlr** [comment]
Thanks for your help. 

Unfortunately I ran into 2 issues: 
 1. `pkg_zip` does not have an `include_runfiles` argument
 2. using `pkg_tar`, the set of runfiles seems to be too big, e.g. `System.Collections.dll` should not be included as that is provided by AWS Lambda

**Comment by purkhusid** [comment]
@njlr Sorry, I forgot to respond to you and was going through the issues now.

Regarding the runfiles list being too large then I think I'll try to find a way to have 2 different `fsharp/csharp_binary` rules where one behaves like `dotnet publish -r <os-arch>` which would include the runtime and the other one would not include the runtime.

I don't think I'll add it to the `master` branch but the `next` branch since we are actively working on all kinds of improvements there.

**Comment by njlr** [comment]
Thanks @purkhusid. 

I was thinking a design like this could work well:

```starlark
fsharp_library(
  name = "foo",
  srcs = [
    "Library.fs",
  ],
)

dotnet_publish(
  name = "foo_pub",
  lib = ":foo",
)
```

**Comment by purkhusid** [comment]
There is now an `publish_binary` rule on the `next` branch that can publish self contained and framework dependent binaries.
Examples are in the `examples` folder.
