### ISSUE TITLE
`nuget2bazel` package source authentication 

### ISSUE THREAD

**Issue by epickrram** [bazelbuild/rules_dotnet#291]
Hi folks,
thanks for the great work so far.

I am using the latest version from master, but having issues consuming packages from a custom nuget source.

The feed is hosted by a 3rd party, and requires authentication. When I try to use `nuget2bazel` (as per the docs [here](https://github.com/bazelbuild/rules_dotnet/blob/master/docs/nuget2bazel.md#the-tool)), I get an authorization error:

```
INFO: Running command line: \
  bazel-bin/external/io_bazel_rules_dotnet/tools/nuget2bazel/nuget2bazel.exe/nuget2bazel.exe_0.exe \
  add -p $PROJECT_DIR -u -n <authenticated-feed-url>
...
Unhandled exception. NuGet.Protocol.Core.Types.FatalProtocolException: \
  Unable to load the service index for source https://HHHH/XXXX/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: \
   401 (Unauthorized).
```

It looks like the sensible place to apply authentication would be here:

https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/AddCommand.cs#L46

but there doesn't seem to be any way to add credentials.

Is there a mechanism in place for doing so? Looking at the work happening on the `next` branch, it seems that the plan is to replace `nuget2bazel` with `paket`. If that's the plan, will the `paket` workflow allow for authentication against 3rd-party nuget sources?

**Comment by purkhusid** [comment]
@epickrram Thanks for flagging this! Currently there is no way to add authentication on the `master` branch.

The current `nuget2bazel` tool will be deprecated when the `next` branch will be merged into `master` in favour of either `paket2bazel` which will work well if you are already using Paket(https://fsprojects.github.io/Paket/) or a new `nuget` tool that was recently added to the `next` branch.

It's on the TODO list to add authentication for private repositories but it has not yet been added to the `next` branch. It will probably be my co-maintainer @tomdegoede  that implements this feature at some point since he has actual need for it.

**Comment by tomdegoede** [comment]
@epickrram you could try adding the credentials to nuget.config using packageSourceCredentials. I'm not sure however if the nuget2bazel implementation in master consumes the nuget config by default.

**Comment by epickrram** [comment]
@purkhusid @tomdegoede thank you for the responses; I'll try out those suggestions.
