### ISSUE TITLE
Creating Releases 

### ISSUE THREAD

**Issue by superNodeman** [bazelbuild/rules_dotnet#306]
I wanted to ask if there are any short term plans or abilities to create releases for rules_dotnet? I think this may have been alluded to in the conversations in #260? We would like to use this for our bazel builds at work but we use artifactory for our external dependencies and other projects like rules_java have releases that we can pull down through their releases. There may be another way for us to use rules_dotnet through artifactory? Any suggestions would be appreciated.

**Comment by purkhusid** [comment]
The plan is to start cutting releases once the `next` branch has been merged. I've got some of the infrastructure already but we still have a few things to clean up before I feel comfortable merging the branch. We'll probably continue with 0.x releases for a while since it can take some time for the public part of the rules to become stable.

**Comment by purkhusid** [comment]
The first release was just cut: https://github.com/bazelbuild/rules_dotnet/releases
