### ISSUE TITLE
Question: test data for MS Build and rules_dotnet

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_dotnet#331]
I am trying to maintain MS Build and rules_dotnet targets together. The goal is to have both work on the same code. Things are complicated by the fact that my tests require some test data at run-time. 

In MS Build the target looks like this:

`foo_tests/foo_tests.fsproj`

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\foo\foo.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="testdata/**/*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

In Bazel rules_dotnet, it looks like this:

`foo_tests/BUILD.bazel`

```starlark
load("@rules_dotnet//dotnet:defs.bzl", "fsharp_test")

fsharp_test(
  name = "foo_tests",
  srcs = [
    "Program.fs",
  ],
  target_frameworks = [
    "net6.0",
  ],
  data = glob([
    "testdata/**/*.json",
  ]),
  deps = [
    "@paket.main//microsoft.netcore.app.ref",
    "@paket.main//fsharp.core",
    "@paket.main//expecto",
    "//foo",
  ],
)
```

The issue is the location of the test JSON files. They are loaded in tests like this:

```fsharp
let test1 =
  testAsync "test_1.json" {
    use stream = File.OpenRead("testdata/test_1.json")

    // ...
  }
```

I want both of these to work with the same code:

```bash
dotnet test ./foo_tests

bazel test //foo_tests:foo_tests
```

However, 

 - MS Build puts the test data at `testdata/test_1.json`
 - And Bazel puts the test data relative to the workspace root at `foo_tests/testdata/test_1.json`

Is there a simple way to tweak the Bazel target so that the test files will be available in the same directory as for MS Build?

Alternatively, can the test executable be run from the directory it is defined in?

**Comment by purkhusid** [comment]
This is really one of the places where Bazel and other build systems have a pretty hard time coexisting. The `data` attribute is pretty well defined(https://bazel.build/reference/be/common-definitions#typical-attributes) and the Bazel idiomatic way of looking up files that are in the `data` attribute is to use a runfiles library. 

I implemented a Runfiles library for rules_dotnet and an example can be found in the `examples` folder.

I think I might be open to an contribution that adds an attribute that copies files to a folder relative to the target. It might make it easier for people to migrate from MSBuild to Bazel.
It could be something like:

```
copy_to_output_directory = {
    "some/folder/**/*.md":  "some/output/path"
}
```
The only thing I'm a bit worried about how this would behave when you have this attribute set in e.g. a `*_library` that is a dependency in a `*_binary` which is then used in a  `dotnet_binary_publish` target.

Also a concern is what happens when two dependencies have clashing file paths.

**Comment by njlr** [comment]
I found this to be a reasonable work-around:

```fsharp
[<EntryPoint>]
let main args =

  let runfilesDir =
    Environment.GetEnvironmentVariable("RUNFILES_DIR")
    |> Option.ofObj

  match runfilesDir with
  | Some _ ->
    // We are running under Bazel so we need to `cd` to the correct directory for the test data
    let currentDirectory = Directory.GetCurrentDirectory()
    let workingDirectory = Path.Combine(currentDirectory, "foo_tests") // Name of the Bazel package

    printfn $"Moving from \n\n  %s{currentDirectory} \n\nto\n\n  %s{workingDirectory}\n\n"

    Directory.SetCurrentDirectory(workingDirectory)
  | None -> ()

  runTestsWithCLIArgs [] args tests
```

The `copy_to_output_directory` idea sounds excellent.

**Comment by purkhusid** [comment]
Closing this since I don't plan on adding any more functionality and I recommend that people use the runfiles library to resolve `data`.
