### ISSUE TITLE
Is It Possible To Use On Windows?

### ISSUE THREAD

**Issue by jared-bott** [bazelbuild/rules_dotnet#56]
I've been trying to use bazel to build C# libraries on Windows 10, with no success. I'm trying to build rules_dotnet as an initial test.

Initially, bazel says that mono isn't supported on Windows 10. Following that, I set an environment variable `RULES_DOTNET_USE_LOCAL_MONO` equal to 1. After that, bazel said that `MONO` needed to be set; after reading through `csharp.bzl`, I set `MONO` to the path to Mono, e.g. `C:\Program Files\Mono\`. I'm not really sure if this is the correct location to set it to. I also set `CSC` as an environment variable pointing to a variety of locations for mcs and csc (`C:\Program Files\Mono\bin\mcs.bat`, `C:\Program Files\Mono\lib\mono\4.5\csc.exe`, `C:\Program Files\Mono\lib\mono\4.5\mcs.exe`). None of these work. When I run `bazel build ...`, I get a message:

```
ERROR: missing input file '@mono//bin:mono'
ERROR: C:/meta/rules_dotnet/examples/example_tool/BUILD:13:1: //examples/example_tool:hello_single_output: missing input file '@mono//bin:mono'
ERROR: C:/meta/rules_dotnet/examples/example_tool/BUILD:13:1 1 input file(s) do not exist
```

This led me to add a print statement to see the path to mcs. In `csharp.bzl`, in `_csc_compile_action`, I've tried printing out `ctx.file.csc.path`, and get `external/mono/bin/mcs`. Since this didn't seem correct, I looked into how the location of csc is set and saw that I can set it in the BUILD files for the library. I added a `csc = ` line to the example library's BUILD, but that doesn't fix the issue.

I've tried setting `MONO` to csc (`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe`), as well as pointing `CSC` to the same location, but that didn't work either.

Can you provide any guidance? Is it just not possible?

**Comment by j3parker** [comment]
Did it create the symlink `external/mono/bin/mcs`? Where does it point to if yes?

Rather than using `RULES_DOTNET_USE_LOCAL_MONO` try setting the argument to `True` in the call to `csharp_repositories`. This is a little less annoying than an environment variable (Bazel runs a background process, I'm guessing its environment variables are used, so if you're attempting to change it by tweaking the environment of `bazel` the cli tool it may not work.)

I don't think these rules ever ran on Windows; just Linux and Mac. It's probably not a huge lift to make them work for mono equivalently on Windows though, for whatever that's worth. 

Setting mono to csc will definitely not work. These rules don't support .NET Framework/Windows (I don't know what it'd take to make mono+Windows work but that might be pretty easy.) I've documented a bit of the work remaining in issue #54.

If you get it working note that these rules are very much a proof-of-concept. There is functionality that is missing before you can build realistic C# projects with these rules.

I have a private fork that supports a lot more stuff (including Windows, but .NET Framework only at the moment) that I'm slowly trying to upstream. If you're really keen/interested in helping you can contact me at Jacob.Parker@D2L.com.

**Comment by tomaszstrejczek** [comment]
Yes, the new toolchains-based implementation supports windows.
