### ISSUE TITLE
The type initializer for 'NuGet.ProxyCache' threw an exception

### ISSUE THREAD

**Issue by jawsthegame** [bazelbuild/rules_dotnet#57]
Getting this error when trying to use RestSharp (or any library) from NuGet.
Here is my nuget_package:

```
nuget_package(
  name = "rest_sharp_102_7_0_0",
  package = "RestSharp",
  version = "102.7.0.0",
)
```

And here is the error:
```
/opt/app/client/dotnet/BUILD:3:1: no such package '@rest_sharp_102_7_0_0//':
Nuget command failed: The type initializer for 'NuGet.ProxyCache' threw an exception.
  libc
```

Any thoughts here? I also get that same error when I run nuget.exe directly. I installed mono on ubuntu by installing the default `mono_devel` package.

**Comment by j3parker** [comment]
Can you provide the output of `mono --version`?

**Comment by jawsthegame** [comment]
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

HTTP_PROXY and NO_PROXY are not defined.

**Comment by j3parker** [comment]
Could you check `http_proxy` and `no_proxy` (lower case)?

**Comment by jawsthegame** [comment]
those are also undefined

**Comment by jawsthegame** [comment]
that `rest_sharp_102_7_0_0` target is defined in my workspace, so here is the output when building just `:dylibs` for that package:

```
$ bazel build @rest_sharp_102_7_0_0//:dylibs

ERROR: Skipping '@rest_sharp_102_7_0_0//:dylibs': no such package '@rest_sharp_102_7_0_0//': Nuget command failed: The type initializer for 'NuGet.ProxyCache' threw an exception.
  libc
 (/home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/mono/bin/mono --config /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/mono/bin/../etc/mono/config /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/nuget/nuget.exe install -Version 102.7.0.0 -OutputDirectory /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/rest_sharp_102_7_0_0 RestSharp)
WARNING: Target pattern parsing failed.
ERROR: no such package '@rest_sharp_102_7_0_0//': Nuget command failed: The type initializer for 'NuGet.ProxyCache' threw an exception.
  libc
 (/home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/mono/bin/mono --config /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/mono/bin/../etc/mono/config /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/nuget/nuget.exe install -Version 102.7.0.0 -OutputDirectory /home/builduser/.cache/bazel/_bazel_builduser/8cd13b75700216788cbc2043831c737d/external/rest_sharp_102_7_0_0 RestSharp)
INFO: Elapsed time: 0.323s
```

**Comment by j3parker** [comment]
Hm. I'd expect the error is coming from [here](https://github.com/NuGet/NuGet.Client/blob/4cccb13833ad29d6a0bcff055460d964f1b49cfe/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L21) (the type initializer is the static constructor/static initializers for this type.)

You mentioned the same thing happens if you invoke nuget manually. Is there any extra error output? E.g. which exception was thrown, or a stack trace? [This](http://www.mono-project.com/docs/debug+profile/debug/) indicates that passing `--debug` to mono will provide some extra details (I'm not a mono expert.)

**Comment by jawsthegame** [comment]
Unfortunately --debug doesn't give any additional output.

**Comment by zaphar** [comment]
If you get the same error when running nuget manually then this may not be
a problem with the Bazel rules.

You may want to ask the Nuget developers and check if there is a known
issue with Nuget that you've run into.


On Mar 6, 2018 16:19, "Tom Fleischer" <notifications@github.com> wrote:

Unfortunately --debug doesn't give any additional output.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/rules_dotnet/issues/57#issuecomment-370949557>,
or mute the thread

**Comment by jawsthegame** [comment]
Fair enough.
