### ISSUE TITLE
Adding reference to System.Data.dll

### ISSUE THREAD

**Issue by lx223** [bazelbuild/rules_dotnet#58]
Hi there, I might have missed something somewhere. How could I easily add assemblies bundled with mono easily, such as `System.Data.dll`?

**Comment by j3parker** [comment]
You can use the [`dll_import`](https://github.com/bazelbuild/rules_dotnet#dll_import) rule to bring in external DLLs.

Where I work, on Windows, we include this in the `csharp_respostories` workspace macro:

```python
def csharp_repositories(net_framework_path):
  
  # ...
  
  native.new_local_repository(
    name = "NETFramework",
    path = net_framework_path,
    build_file = "@d2l//build/bazel/dotnet:netsdk.BUILD",
  )
```

and the contents of that build file are

```python
package(default_visibility = ["//visibility:public"])

load("@rules_d2l//dotnet:csharp.bzl", "dll_import")

[dll_import(
  # bad impl of basename (switch to skylib?)
  name = p[len(p) - p[::-1].index("/") if "/" in p else 0:-len(".dll")],
  srcs = [p],
) for p in glob(["**/*.dll"])]
```

This gives us labels like `NETFramework//:System.Data` that we can add to `deps`. It's not perfect but it's working for us for now.

**Comment by j3parker** [comment]
I suppose I should add that wiring stuff up approximately like this in Bazel is "correct" because Bazel caches based on the content of all the inputs, so you want to teach Bazel about each of those System DLLs. This matters if you upgrade mono (that should cause things to rebuild) or if you share a cache across multiple machines.

The reason that isn't done automatically by these rules yet is that they are basically prototypes. I think the correct design for these rules will eventually involve toolchains and by default vendoring the compiler and framework (tricky for .NET framework on Windows though.)

**Comment by tomaszstrejczek** [comment]
In the new implementation you just reference "@io_bazel_rules_dotnet//dotnet/stdlib:System.Data.dll". The declarations from the most common assemblies are provided by rules in dotnet/stdlib.
