### ISSUE TITLE
More nuget documentation

### ISSUE THREAD

**Issue by thelgevold** [bazelbuild/rules_dotnet#73]
Hi. Thanks for updating the .net rules!

I gave it a try, and was able to put together a working sample relatively quickly. The only issue I had was with the nuget rule. 

I am wondering if it would be possible to clarify the nuget rules a bit more. I am curious why we have to specify so many details about the dlls in the package. In regular .Net, all you have to specify is the name of the package.

Here is a quick write up of the sample that I did: http://www.syntaxsuccess.com/viewarticle/building-dotnet-with-bazel

**Comment by tomaszstrejczek** [comment]
In regular .NET, msbuild rules during compilation extracts all necessary metadata from nuget packages to properly reference assemblies (depending mainly on target framework). Bazel, by design, cannot do it during compilation. Therefore, I created a dedicated tool which tries to generate proper workspace rules:

https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst

[https://avatars1.githubusercontent.com/u/11684617?s=400&v=4]<https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst>

bazelbuild/rules_dotnet<https://github.com/bazelbuild/rules_dotnet/blob/master/tools/nuget2bazel/README.rst>
github.com
.NET rules for Bazel. Contribute to bazelbuild/rules_dotnet development by creating an account on GitHub.



Regards,

   Tomasz




________________________________
Od: Torgeir Helgevold <notifications@github.com>
Wysłane: niedziela, 7 października 2018 04:31
Do: bazelbuild/rules_dotnet
DW: Subscribed
Temat: [bazelbuild/rules_dotnet] More nuget documentation (#73)


Hi. Thanks for updating the .net rules!

I gave it a try, and was able to put together a working sample relatively quickly. The only issue I had was with the nuget rule.

I am wondering if it would be possible to clarify the nuget rules a bit more. I am curious why we have to specify so many details about the dlls in the package. In regular .Net, all you have to specify is the name of the package.

Here is a quick write up of the sample that I did: http://www.syntaxsuccess.com/viewarticle/building-dotnet-with-bazel<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.syntaxsuccess.com%2Fviewarticle%2Fbuilding-dotnet-with-bazel&data=02%7C01%7C%7Cad40e3712a4d48c991ee08d62bfd02cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636744762998501232&sdata=1CFRWKbrdsSDao9LACB5zBKgC351pP6hx6MFSM8BQ%2F0%3D&reserved=0>
