### ISSUE TITLE
Need support for /noconfig compiler command line switch

### ISSUE THREAD

**Issue by jimevans** [bazelbuild/rules_dotnet#83]
In the `net_library` rule, when specifying to compile against a legacy framework version like .NET 3.5, the reference assemblies get resolved properly, but the build fails when executing the C# compiler. This is because there is a response file in the directory with the compiler itself (`csc.rsp`) which specifies framework references already. However, these specified references are not the correct versions, as those references get resolved to a different framework version.

There is a command line switch for the C# compiler that allows the user to bypass the built-in response file in favor of explicitly specifying framework assembly references. This is the same thing Visual Studio does when it calls the compiler, using the `/noconfig` command line switch to avoid the automatic resolution of framework assembly references.

Note carefully that this command line switch cannot be added to the parameters file that gets created by the current rule, as it gets ignored when present in a parameters file. It _must_ be part of the actual command line executing `csc.exe`.

**Comment by tomaszstrejczek** [comment]
Yes, I missed it. Thanks.
Fixed with https://github.com/bazelbuild/rules_dotnet/commit/bdfc24001b2463dbdb483b1fd9cd6420002adc7d

________________________________
Od: Jacob Parker <notifications@github.com>
Wysłane: wtorek, 11 grudnia 2018 19:04
Do: bazelbuild/rules_dotnet
DW: tomaszstrejczek; Mention
Temat: Re: [bazelbuild/rules_dotnet] Need support for /noconfig compiler command line switch (#83)


@tomaszstrejczek<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftomaszstrejczek&data=02%7C01%7C%7C43932897d4824b59181708d65f932a8e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636801483004541825&sdata=VK2elg0PIUgwqEhgAereRZQm3RgA6xu1AgNOz4xHDsg%3D&reserved=0> you added /noconfig to the arguments that go into a param file. @jimevans<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimevans&data=02%7C01%7C%7C43932897d4824b59181708d65f932a8e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636801483004541825&sdata=wf8P0q5fAATW65UqXv7%2BPB5unTSxs3SC7X5QyLvbdnA%3D&reserved=0> explained why that won't work at the bottom of his comment.

**Comment by j3parker** [comment]
Thanks!
